name: Update ICS (Europe/Berlin)

on:
  schedule:
    - cron: "0 */6 * * *"      # alle 6h (UTC)
  workflow_dispatch:

permissions:
  contents: write              # erlaubt Commit/Push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch ICS with retries (non-fatal on 500)
        id: fetch
        env:
          SOURCE_ICS_URL: ${{ secrets.SOURCE_ICS_URL }}
        run: |
          set -e
          echo "Fetching $SOURCE_ICS_URL"

          # Cache-Buster anhaengen (hilft bei launischen 500ern/Caches)
          TS=$(date +%s)
          URL="$SOURCE_ICS_URL"
          case "$URL" in
            *\?*) URL="${URL}&nocache=${TS}" ;;
            *)    URL="${URL}?nocache=${TS}" ;;
          esac

          # Versuch 1: 'saubere' Header + Retries
          if ! curl -fsSL \
               -H "Accept: text/calendar" \
               -H "Cache-Control: no-cache" \
               -A "Mozilla/5.0 (compatible; ICSFetcher/1.0)" \
               --retry 6 --retry-delay 10 --retry-all-errors --retry-connrefused \
               "$URL" -o source.ics; then
            echo "Try #1 failed, trying alternative headers/agent..."
            # Versuch 2: alternative Header/Agent
            curl -fsSL \
              -H "Accept: */*" \
              -H "Pragma: no-cache" \
              -A "curl/8.x github-actions" \
              --retry 6 --retry-delay 10 --retry-all-errors --retry-connrefused \
              "$URL" -o source.ics || true       - name: Fetch ICS with retries (non-fatal on 500)
        id: fetch
        env:
          SOURCE_ICS_URL: ${{ secrets.SOURCE_ICS_URL }}
        run: |
          set -e
          echo "Fetching $SOURCE_ICS_URL"

          # Cache-Buster gegen launische Server/Caches
          TS=$(date +%s)
          URL="$SOURCE_ICS_URL"
          case "$URL" in
            *\?*) URL="${URL}&nocache=${TS}" ;;
            *)    URL="${URL}?nocache=${TS}" ;;
          esac

          # Versuch 1 (mehrfach, 'freundliche' Header)
          curl -fsSL \
            -H "Accept: text/calendar" \
            -H "Cache-Control: no-cache" \
            -A "Mozilla/5.0 (compatible; ICSFetcher/1.0)" \
            --retry 6 --retry-delay 10 --retry-all-errors --retry-connrefused \
            "$URL" -o source.ics || true

          # Wenn noch nichts da: Versuch 2 (alternative Header/Agent)
          if [ ! -s source.ics ]; then
            curl -fsSL \
              -H "Accept: */*" \
              -H "Pragma: no-cache" \
              -A "curl/8.x github-actions" \
              --retry 6 --retry-delay 10 --retry-all-errors --retry-connrefused \
              "$URL" -o source.ics || true
          fi

          # Validierung: Nur wenn wirklich ICS, dann "valid=true"
          if [ -s source.ics ] && head -n 1 source.ics | grep -q "BEGIN:VCALENDAR"; then
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "WARN: Keine gültige ICS (500/HTML). Behalte letzte Version."
            echo "valid=false" >> $GITHUB_OUTPUT
          fi

          fi

          # Wenn wir hier keine gueltige ICS haben, scheitern wir NICHT,
          # sondern lassen die alte konfi.ics bestehen.
          if [ ! -s source.ics ] || ! head -n 1 source.ics | grep -q "BEGIN:VCALENDAR"; then
            echo "WARN: Outlook lieferte keine gueltige ICS (500/HTML). Behalte letzte Version."
            echo "valid=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "valid=true" >> $GITHUB_OUTPUT

      - name: Normalize timezone to Europe/Berlin (only if valid)
        if: steps.fetch.outputs.valid == 'true'
        run: |
          sed -e 's/TZID:W\. Europe Standard Time/TZID:Europe\/Berlin/g' \
              -e 's/DTSTART;TZID=W\. Europe Standard Time/DTSTART;TZID=Europe\/Berlin/g' \
              -e 's/DTEND;TZID=W\. Europe Standard Time/DTEND;TZID=Europe\/Berlin/g' \
              source.ics > konfi.ics

          if ! grep -q "^X-WR-TIMEZONE:" konfi.ics; then
            awk '1; /^X-WR-CALNAME:/ {print "X-WR-TIMEZONE:Europe/Berlin"}' konfi.ics > tmp && mv tmp konfi.ics
          fi

      - name: Commit updated ICS (only if changed and valid)
        if: steps.fetch.outputs.valid == 'true'
        run: |
          set -e
          git config user.name  "calendar-bot"
          git config user.email "bot@example.com"
          if [ ! -f konfi.ics ] || ! git diff --quiet -- konfi.ics 2>/dev/null; then
            git add konfi.ics
            git commit -m "Update ICS (auto)"
            git push
          else
            echo "No changes."
          fi
